config/routes.rb
Rails.application.routes.draw do
  resources :messages
  get 'callback/index'
  post '/' => 'callback#recieved_data'
  get 'callback/recieved_data'
  root 'callback#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    if params["hub.verify_token"] == "asd"
      render text: params["hub.challenge"]
    end
  end

  def recieved_data
    therequest = request.body.read
    data = JSON.parse(therequest)
    enteries = data["entry"]
    enteries.each do |entry|
      entry["messaging"].each do |messaging|
        sender = messaging["sender"]["id"]
        text = messaging["message"]["text"]
        myjson = {"recipient": {"id": "#{sender}"},"message": {"text": "Thanks for messaging us!"}}
        puts HTTP.post(url, json: myjson)
      end  
    end
    render "received_data"
  end

  def url
    "https://graph.facebook.com/v2.6/me/messages?access_token=EAANHofZB14DUBAPfWxY6GOAkpKZBl58cVYNSMOCmpxzc5N4OQoBwsiUMjkWTSZBUyCr3H7uJ1rCgdRoPcFZAxE3rh9FzYk612yC36ffN6NVn3zahwecXIhcO03AaQUN2XXmrdD55tDcgwIQZAMVtIZCkbONAzBWZA1ZA0kcLOj7wlNNTyPsDuowX"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:received, :reply)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/callback/index.html.erb
<h1>Callback#index</h1>
<p>Find me in app/views/callback/index.html.erb</p>

app/views/callback/received_data.html.erb
<h1>Callback#received_data</h1>
<p>Find me in app/views/callback/received_data.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatbot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :received, style: "display: block" %>
    <%= form.text_field :received %>
  </div>

  <div>
    <%= form.label :reply, style: "display: block" %>
    <%= form.text_field :reply %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Received:</strong>
    <%= message.received %>
  </p>

  <p>
    <strong>Reply:</strong>
    <%= message.reply %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>